spring:
  application:
    name: currency-conversion


server:
  port: 8004
  servlet:
    context-path: /currency-conversion

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    lease-renewal-interval-in-seconds: 10



feign:
  client:
    config:
      forex-service:
          connectTimeout: 5000
          readTimeout: 5000
          loggerLevel: FULL
ribbon:
  eureka:
    enabled: false
